### PR TITLE
Adding repositories file

### PR DESCRIPTION
**Pull request by farnasirim**
Originally in ~/.kupak/repos

### CODE REVIEW

**Comment by alaee** [comment]
این تودو‌هاش چیه؟

**Comment by alialaee** [comment]
تودوهاش چیه؟

**Comment by farnasirim** [comment]
The only thing that comes to my mind is that kupak needs to provide functionality for interacting with the repos file. (e.g. kupak repo add github.com/foo/bar). Do you have anything else in mind?

**Comment by farnasirim** [comment]
How about being able to change the path from which kupak reads the repos file + allowing for comments in the repos file?

**Pull request merged**
